### PR TITLE
a kind documentation/errata of celluloid-related memory leaks

### PR DESCRIPTION
**Pull request by niamster**

### CODE REVIEW

**Comment by digitalextremist** [comment]
@niamster ready to merge this into the prerelease? It looks complete?

**Comment by e2** [comment]
Is there actually a reason to have this test skippable?

**Comment by niamster** [comment]
@digitalextremist yes, it looks complete for me. If I remove 'include Celluloid' from the target class the test is passed with 90% probability.
@e2 it's skipped by default but put into 'allowed failures' for Travis. The reason is that there are still leaks that are linked to ruby itself rather than Celluloid and there's no clean solution to avoid them(see #463)

**Comment by e2** [comment]
@niamster - if I understand correctly, this spec should be enabled on jruby and rbx (because it's expected to pass) and it should be always disabled on MRI (until there's a workaround).

Either a test can pass 100% of the time - and should be enabled (on whatever platforms support it), or disabled completely (until it works 100% of the time on MRI as well).

I think of this as a test protecting against *introducing* certain memory leaks - and so it should enabled everywhere it can.

Also, think of JRuby (and RBX) as the *main* interpreters for Celluloid. MRI is the one that should have special patches to match the behavior of the other two.

**Comment by digitalextremist** [comment]
I'm a bit off radar today but just wanted to say: I believe it's the opposite @e2. MRI isn't leaking and jRuby / rbx are. So those will fail unless @niamster figured out how to work around this. I saw `Fiber.yield` come in, so maybe he did!

**Comment by niamster** [comment]
@digitalextremist I didn't try these tests with rbx and jruby.

**Comment by niamster** [comment]
Going to push new one with a changeset which fixes one of the leaks in MRI.

**Pull request closed without merging**
