### PR TITLE
interim batch of code going into prerelease

### PR DESCRIPTION
**Pull request by digitalextremist**
Keep the official prerelease current with the "low-traffic" fork where work is happening.

### CODE REVIEW

**Comment by e2** [comment]
I reviewed this. I'm not too happy - lots of stuff that should be refactored, reworked, etc. I'm pushing to get everything green first, though. (Otherwise, refactoring makes little sense).

**Comment by digitalextremist** [comment]
@e2 definitely agreed. This *does not* imply this code is presentable, only preventing getting too far out of sync, and bringing whatever state the code is in to the attention of our fellows.

Please, by the way, open a parallel branch for experiments you're doing, such as `0.17.0-experiments` and extract into that branch transient code you brought in. Really whacky errors are going on, whether the tests are passing or not. But I guess it's showing where the test suite is lacking. This issue is particularly frightening: celluloid/celluloid-fsm#1

**Comment by e2** [comment]
@digitalextremist - it's a long trip:

green tests -> consistently green tests -> no errors -> no warnings -> hardening test suite -> diagnostics/instrumentation -> stress tests -> coverage -> rubocop ...

Coverage will help a lot with your issues, but notice how far down the line it is...

**Comment by digitalextremist** [comment]
@e2 I understand the process of writing good software. What I'm talking about is *understanding the code we currently have in the release* and while I'm following issues through from start to finish and crossing them off, the floor beneath me is turning into air and then water and becoming a gas and I'm just like `whoa` so I never thought I'd say or think something in these terms, but let's "diminish the Ayahuasca factor" of `0.17.0` with a seriousness. Right now we can let the perfection that is `1.0` be handled in steps, and just focus on one good release on the way there.

**Comment by digitalextremist** [comment]
Consolidating and moving back to official repository, then going to need to do a much larger review of the prerelease.

**Pull request merged**
