### PR TITLE
memory leak battle

### PR DESCRIPTION
**Pull request by niamster**
changes:
   - rebase onto the tip of 0.17.0-prerelease
   - fixed memleaks:
     - method args and return value on MRI/2.2
     - method return value in jruby
     - get rid of object space module as it's not supported in rbx or jruby

### CODE REVIEW

**Comment by digitalextremist** [comment]
:+1: merging

**Comment by digitalextremist** [comment]
@niamster this PR has dramatically improved the stability of celluloid from what I've so far seen. Thank you for your work on this!

**Comment by niamster** [comment]
@digitalextremist really? That's interesting. Anyway I will continue to work especially on the leak of the actors.

**Comment by marshall-lee** [comment]
@niamster could you explain these MRI- and JRuby-specific issues? Very interesting!

**Comment by digitalextremist** [comment]
In my understanding, #463 goes deeply into that @marshall-lee.

**Pull request merged**
