### PR TITLE
Hide RuboCop offenses #538

### PR DESCRIPTION
**Pull request by e2**
Disabled all the current RuboCop offenses using the .rubocop_todo.yml.

(Offenses listed there can be selectively re-enabled and fixed on an ongoing basis).

### CODE REVIEW

**Comment by digitalextremist** [comment]
@e2 what about keeping the live file and just commenting them all out for now?

**Comment by digitalextremist** [comment]
@e2 do we need this? Is this going to matter long enough to commit it?

**Comment by e2** [comment]
Yes, but let me know when you're done with all work and ready to merge to master (it should be the last step given all the work you're doing) and I'll re-do this commit (to reflect the codebase).

After that, you and Tony should go through the list to decide what to enforce and what should stay as "ignored". And *then* when can close this, and *then* someone can fix the offenses so you and Tony and happy.

Otherwise, the RuboCop version bump alone is important.

**Comment by digitalextremist** [comment]
@e2 roger that; bump the version for now, in `0.17.0-prerelease`, then we'll come back to this and I will pair with @tarcieri to comb through this before we push `0.17.0`

**Comment by digitalextremist** [comment]
( @tarcieri, I was hoping to ship `0.17.0` before GSoC started officially. But it might help to go through `0.17.0` in person, for stuff like this, and to get first hand from you the remaining roadmap versus what right now I've projected. I need to go to Mexico in the first week of May, but then after that I can probably come up for end-of-release stuff like this; back-of-the-mind FYI )

**Comment by digitalextremist** [comment]
As it stands, everything in the prerelease is currently marked "false" without inheriting from a secondary file, so I'm going to close this and we can readdress it at #538 later.

**Pull request closed without merging**
