### PR TITLE
memory leak battle

### PR DESCRIPTION
**Pull request by niamster**
changes:
 * rebase onto the tip of 0.17.0-prerelease
 * fixed memleaks:
  - method args and return value on MRI/2.2
  - method return value in jruby
  - get rid of object space module as it's not supported in rbx or jruby

### CODE REVIEW

**Comment by niamster** [comment]
Argh, a typo after rebase.

**Comment by e2** [comment]
@niamster - great stuff. 

I find the mailbox code quite confusing with the timers, checking, locks, receive()+check() API ... and that break returning a message (which was a break from the timer loop).

**Comment by niamster** [comment]
@e2 not so tricky IMHO. What I hate here is that we have to violate nice ruby syntax to avoid memory leak =|

**Comment by tarcieri** [comment]
@niamster no worries about syntactic beauty. Make it work then make it beautiful :wink:

**Comment by digitalextremist** [comment]
@niamster the followup #585 to this was *functionally* beautiful. It has really helped with the fractures I've been seeing. Celluloid is starting to behave like itself again.

**Pull request closed without merging**
