### PR TITLE
Refactor test suite.

### PR DESCRIPTION
**Pull request by digitalextremist**
This is a single review point for @e2's many changes to the test suite per #526, and any other contributions/revisions brought in. Please address revision PR's to this branch `refactor-test-suite`

### CODE REVIEW

**Comment by digitalextremist** [comment]
Now celluloid/celluloid-io#134 is depending on this code.

**Comment by digitalextremist** [comment]
@e2 what's your reasoning for marking `1.9.3` as an allowed failure?

**Comment by digitalextremist** [comment]
IMO, the stable versions of `jruby`, `rbx`, and `1.9.3` ought to be mandatory successes, we have a *lot* of code deployed in those environments. Where are you coming from with that thought @e2?

**Comment by e2** [comment]
@digitalextremist - ironically, the failures are probably just test-env specific. 1.9.3 can be mandatory already, since it's green. JRuby may take time to get to green, and Rbx might be a lost cause (not enough support to deal with the complexity of the test environment + threads).

It's not hard for a test env to crash JRuby or RBX - especially because RSpec does a lot of magic there. Also, the Celluloid boot/shutdown between each tests isn't "normal".

What I'm saying is: it may not even be possible to get the all the tests green by "fixing" them - it may become just about side-stepping bugs in interpreters (and not Celluloid itself).

**Comment by digitalextremist** [comment]
@e2, OK. I hear you. For now I'll settle for `1.9.3` being mandatory out-of-the-box, and we can think further about beating the high performance twin RVMs into submission somehow.

**Comment by digitalextremist** [comment]
*mandatory

**Comment by digitalextremist** [comment]
@tarcieri the CI tests doubled ( again ). If this is a problem I will refactor that, but I set these conditions, following @e2's changes. This will only last until #524 is resolved.

* Use `TaskFiber`, bypass `:flaky`
* Use `TaskFiber`, do not bypass `:flaky`
* Use `TaskThread`, bypass `:flaky`
* Use `TaskThread`, do not bypass `:flaky`

Then all but use `TaskFiber`, bypass `:flaky` are allowed failures.

**Comment by digitalextremist** [comment]
I wonder if we should just not use `TaskThread` in CI and expect people to test their own situation themselves, by setting `CLLLD_TASK_CLASS=TaskThread`

**Comment by e2** [comment]
@digitalextremist - just hang on for now. I've almost got all TaskThread tests working on JRuby head. Many flaky tests are no longer flaky - and most fixes are due to race conditions and internal termination handling bugs/problems in Celluloid. Just hang in there...

@tarcieri - I'll have a branch put up once I do cleaning up. I'd like to ask for a thorough review though (since I'm making LOTS of assumptions about Celluloid that could be completely wrong or result in horrible performance). Some changes are drastic, like completely reworking how Actor.join is done, disabling termination timeout in favor of specific timeouts per Actor, a potentially slow (for now), mutex-heavy InternalPool (but one that works almost flawlessly in tests, no matter how much banging the tests get), avoiding Thread.kill completely (since you'd need to Einstein to use it correctly on JRuby), etc. Just giving a heads up. ETA - a few days (still some StackDump, Probing issues and supervision issues).

**Comment by e2** [comment]
@tarcieri - I disabled some tests that use Actor.join directly, because this method/API doesn't make sense to me. (If at all, people should just shutdown the Actor instead - it just potentially hangs an app or tests if no timeout is given, while a timeout just destroys any state consistency on JRuby). ThreadHandle.join doesn't make sense to me either (doesn't seem to be used anywhere, either).

**Comment by tarcieri** [comment]
@e2 I can have a look when you're done.

I'm glad you're working on InternalPool as the current implementation was completely broken, but I think I'd actually prefer ditching it completely. It's been the source of a lot of memory leaks, and I think using a more normal thread lifecycle would help avoid those. Just as an example it clears Fiber-local `Thread#[]` but doesn't clear "real thread locals" i.e. `Thread#thread_variable_get/set`, nor does it ensure the death of all Fibers for a thread. Given the complexity involved, I think ditching InternalPool completely is the best option.

**Comment by digitalextremist** [comment]
@tarcieri, yes I'm ditching it currently  ( fyi, @e2 )

**Comment by e2** [comment]
> I'm glad you're working on InternalPool as the current implementation was completely broken

Simply using arrays without locks or instead of queues on JRuby mean "broken".

> but I think I'd actually prefer ditching it completely.

For production - I agree 100%. Even if it's "reimplemented". Though, I'd leave the "fixed" version in spec/support for the sake of "stress testing", especially for JRuby and Rbx.

> It's been the source of a lot of memory leaks, and I think using a more normal thread lifecycle would help avoid those.

It would make debugging much easier if there was just one-thread per task. Not to mention the actual busy/idle management was not clearly defined. Or tested.

> Nor does it ensure the death of all Fibers for a thread.

That actually bit me, because one of the stack_dump spec uses a Fiber and Thread actors. I'm trying to think of threads as coroutines, because they are used that way in Celluloid. Especially to have the same interface as Fibers for task_class.

In fact I learned, Fibers actually can be killed individually on JRuby, because they are threads visible in Thread.list: https://github.com/jruby/jruby/issues/2773

I haven't got to the specs running in Fiber mode yet - I want to make sure all tests pass with Threads first.

> Given the complexity involved, I think ditching InternalPool completely is the best option.

Even if tests are green after retries on Travis ... it doesn't mean the race conditions aren't bugs in Celluloid. So having a "fixed" "reimplementation" of InternalPool could be useful as a helper in spec/support.

It's too easy to "accidentally" get tests green, when they shouldn't be green. Especially since it's hard to predict the side-effects of almost any PR at the moment.

I'd rename the class (so people know not to use it) and have Travis test on the fixed class anyway - until JRuby and Rbx support are good enough. Because Celluloid doesn't really have "unit tests" - they're actually all non-deterministic "stress tests", so even bad implementations have a lot of benefits right now.

What do you guys think?

**Comment by digitalextremist** [comment]
Thanks again for your attention to this layer of things @e2. I think we should allow `InternalPool` to be replaced the same way we do with `.task_class` for Tasks. We can use `.internal_threads_class` or something like that. We can default to the new `Class` coming in for now, then at some point we can totally remove which ever route is least performant and stable... or just leave it there, usually unused like `TaskThread` is. The way `Task*` all "behave as" `TaskThread` is how I'm doing the `InternalPool` replacement -- the API is the same for both... with certain special distinctions which are non-critical differences.

**Comment by digitalextremist** [comment]
I will move `InternalPool` over as part of what I'm doing, unless there's objection to the approach I gave just now. This will allow us to switch on and off the internal thread "collection" just like we do task handlers right now.

**Comment by digitalextremist** [comment]
`Celluloid.group_class` seems short, sweet, and unambiguous.

**Comment by e2** [comment]
> I think we should allow InternalPool to be replaced the same way we do with .task_class for Tasks. 

We think alike - I actually wanted to mention that above - along with the idea to reduce the API:

Users may "want" things like `busy_size` and `idle_size` or have info about threads for the `StackDumper` - but instead, really, it's all available in `Thread.list`. 

(It should be enough to add some examples of things like `Thread#celluloid?` and wrapper class usage to match threads with actors, etc.)

Yet, the biggest reason to drop this extraneous API is: it complicates the internals. 

I've considered e.g. having `busy?` (instead of a useless count) - but anyone tweaking parameters such as max_threads_for_something needs to base calculations on the status of all threads used in the app.

I said useless, because of e.g. "race conditions" for counting existing threads (e.g. a thread can be created and busy - and not yet make it into the internal array). And recycling of threads for tasks makes that exposed info too pool-implementation specific.

As for tests, things like `busy_size` can be replaced with proper mocking (checking e.g. for the right number of get_thread invocations).

**Comment by digitalextremist** [comment]
I agree across the board with what you said. To me that translates to creating a base class the implementations all start from ( like `Reel::Server` ) and we `raise NotImplemented` or something like that for unimplemented/undefined methods... if we even need to do that to keep the tests accurate. Otherwise I am well on my way with `Celluloid.group_class` and sort of wishing `refactor-test-suite` were merged into `master` already, but it'll be fine. I don't think I'm really making conflicts.

**Comment by e2** [comment]
> if we even need to do that to keep the tests accurate

There's too much second-guessing as a contributor. Like, I have no idea if `busy_size` is a "major feature" ... or just there for the tests. (I guess git blame could answer it somewhat).

I think the basic API would be `:get, :put, :grow, :shrink, :shutdown`. grow/shrink = by one - and is only there to "allocate" system resources (so e.g. you can guarantee the pool won't need to allocate new threads after starting - which could potentially fail).

**Comment by digitalextremist** [comment]
@e2 for now let's have the standard be `initialize`, `get`, `shutdown` ( and `kill` ), `create`, `each` ( and `to_a` ) **and that's it** ( pending me forgetting something obvious ) ... Things like `grow`, `shrink`, and `put` are specific to one type of `Group` or more, not all. This non-pool `Group` doesn't need those, so those and `busy_size` and `idle_size` ( which are more for the community to use than `Celluloid` itself ) are not going to be over-ridden base methods.

**Comment by digitalextremist** [comment]
and `running?`

**Comment by e2** [comment]
`each` and `to_a` are either racy or troublesome with mutexes (they can change the flow of things quite a bit - expecially if you query at the wrong time). Using arrays without mutexes (specifically, reading from arrays) on JRuby is a big no-no. They also prevent you from using queues, which don't have the overhead of locks.

**Comment by digitalextremist** [comment]
I will implement this new type of `Group` with `each` and not `to_a` then we can look at its raciness. I'm using `Queues` ... it might not be racy the way I'm doing it.

**Comment by e2** [comment]
As for `running?` - that isn't necessary. Conceptually, it's a "pool" - and you are only about taking or freeing resources, nothing else. `grow` and `shrink` are just optimizations/safety measures. It also raises questions, e.g. is it still `running?` just after calling `shutdown?`. Technically, if you're not just killing everything indiscriminately, it's still "running" until shutdown finishes. You could define 'running' as "empty queues" - but then you have the race condition, because you can allocate and start a thread - without being able to register it (the thread can start running before you have a chance to add it to an internal queue or array).

**Comment by digitalextremist** [comment]
I agree, `running?` and `active?` will be `Group::Pool` specific... which involves an `ActorSystem` tweak I think, but that's fine.

**Comment by e2** [comment]
I got rid of 'kill' actually (had to rework the actor system shutdown code myself). The biggest problems were when shutdown hit the timeout, and then kill was invoked. In JRuby "anything can happen at any time". Literally.

**Comment by tarcieri** [comment]
`Celluloid::Pool` is mostly just broken and needs to be replaced by something else ala `celluloid-coordinator`

**Comment by digitalextremist** [comment]
So far it *seems* like `Celluloid` runs a lot faster without `InternalPool`

**Comment by e2** [comment]
:+1: for a "Celluloid-based supervised pool"

**Comment by e2** [comment]
PoolManager + InternalPool = horrible experience

**Comment by digitalextremist** [comment]
With how radically `TaskPooledFiber` helped things, I'm really curious to see `PoolManager` yanked, as well as `InternalPool` ... and yeah, with those both in the same sentence ... `kill -9 self`

**Comment by digitalextremist** [comment]
I am starting to wonder if removing `InternalPool` and putting in this change I'm about to push isn't going to somehow unmaim `PoolManager` and how we'd know if it did.

**Comment by digitalextremist** [comment]
This is no longer valid, but I'm hesitant to close it in case @e2 is going to hit a wall without it. In a moment though I will be closing this and opening a new PR merging `0-16-5-prerelease` into `master`

**Comment by digitalextremist** [comment]
This is getting convoluted, sorry @e2 I'm switching destination branches to the one linked above:

## The entire test suite passes in under 30 seconds without `InternalPool`*

Except for some lingering `:flaky` tests that sometimes make it ~45-65 seconds.

**Comment by digitalextremist** [comment]
Moved ( for the last time ) to #547

**Pull request closed without merging**
