### PR TITLE
0.17.4 release

### PR DESCRIPTION
**Pull request by ngetahun**
@tarcieri Please take a look if this looks good.

### CODE REVIEW

**Comment by tarcieri** [comment]
@ngetahun the content of the commit looks good, except the base branch for the PR itself needs to be `celluloid:0-17-stable` (it is presently `celluloid:master`)

**Comment by ngetahun** [comment]
> @ngetahun the content of the commit looks good, except the base branch for the PR itself needs to be `celluloid:0-17-stable` (it is presently `celluloid:master`)

Are the release tags created from master or do you create a new branch just for release?

**Comment by tarcieri** [comment]
`master` is presently 0.18.x

**Comment by ngetahun** [comment]
Okay, I'll change the base branch

**Comment by tarcieri** [comment]
All right, wow, I guess this was good to go before. I will merge and release.

**Comment by tarcieri** [comment]
It's out: https://rubygems.org/gems/celluloid/versions/0.17.4

**Pull request merged**
