### PR TITLE
Bring back fix for #696 from #612, in new ::Group::* convention. (take 2)

### PR DESCRIPTION
**Pull request by myers**
This was proposed in PR #763, but we are stuck with rbx-2 not being installable via rvm in travis.

I'm attempting to use the prebuilt binaries that travis says they have here:

http://rubies.travis-ci.org/

### CODE REVIEW

**Comment by tarcieri** [comment]
@myers "something else" didn't work... just delete rbx :cry:

**Comment by myers** [comment]
@tarcieri please let me know if there is anything I can to assist in seeing a 0.17.4 release.

**Comment by tarcieri** [comment]
@myers the main thing that would be helpful is putting together a changelog entry in [CHANGES.md](https://github.com/celluloid/celluloid/blob/0-17-stable/CHANGES.md)

**Comment by tarcieri** [comment]
All right, looking at the history everything interesting is happening on `master`

**Pull request merged**
