### PR TITLE
Example for repeating timer with #every

### PR DESCRIPTION
**Pull request by olleolleolle**
For beginners: an example of `#every`.

 - prints a single line of consecutive numbers (simulating going to sleep counting sheep)
 - added a puts at the end to avoid messing up last line of output
 - the added example is delineated from the rest of the example with a clear class name marker in the output

### CODE REVIEW

**Comment by digitalextremist** [comment]
Good idea! And would you please add `#stop_counting` after the `sleep 1` to illustrate canceling timers, rather than having the death of the main thread end the timer?

You'd just need to store the timer, then cancel it. You could even just `def_delegator` the `cancel` method to an `@timer` instance variable. You know what I mean?

**Comment by olleolleolle** [comment]
(Readability: Focusing on the timer functionality, I skipped the delegation. Is that good/bad?)

**Comment by digitalextremist** [comment]
Oh that's totally fine @olleolleolle, thanks for adding that.

**Comment by digitalextremist** [comment]
I'll merge this in probably in 24-48 hours, before cutting th RC. Thanks again for the example.

**Comment by digitalextremist** [comment]
Thanks @olleolleolle. This is merged, and I corrected two things: `celluloid/current` and using `@sheep`

**Comment by olleolleolle** [comment]
Just pointing out that the attr_accessor allows the previous usage. Now, the attr_accessor :sheep is superfluous.

**Comment by digitalextremist** [comment]
Yeah, I had seen that but strangely it was still erroring out.

**Comment by digitalextremist** [comment]
Ah, because it's being incremented inside a timer block. Withdrawing `attr_accessor`

**Pull request merged**
