### PR TITLE
Update supported Rubies

### PR DESCRIPTION
**Pull request by tarcieri**
1.9.3 is past EOL

2.2.2 is the latest and we should be checking it on Travis

### CODE REVIEW

**Comment by digitalextremist** [comment]
This seems good to go? This was basically done on the next release, but not here on master.

**Comment by tarcieri** [comment]
When you say "good to go", you mean unnecessary, or mergeable?

**Comment by digitalextremist** [comment]
I mean mergeable, or do you have more you were going to add?

**Comment by tarcieri** [comment]
Nope! Merged

**Comment by digitalextremist** [comment]
>> right on <<

**Comment by kostya** [comment]
you can set just 2.1, 2.2 and travis get last minor version

**Comment by digitalextremist** [comment]
@kostya I don't see anything mentioning this behavior on Travis CI, in their examples they specify a minor version number. But also, we tend to need to test point release by point release, so it seems like it would be better to manually specify which minor version number. We've even marked individual point releases as allowable failures since certain point releases sometimes break ( without Celluloid itself being broken ). Make sense?

**Comment by kostya** [comment]
this is rvm behavior, from 2.1, minor version is just patch level.

**Comment by tarcieri** [comment]
@kostya if I use `2.2` in `.travis.yml` it selects 2.2.0, not 2.2.2

**Comment by kostya** [comment]
hm it works with 2.1, and should work with 2.2 too, but travis used not last dvm :(

**Pull request merged**
