### PR TITLE
Bring back fix for #696 from #612, in new ::Group::* convention.

### PR DESCRIPTION
**Pull request by zsiddique**
So this is a patch to make the fix from #696 and apply it to the 0-17-stable branch so a 0.17.4 release can be made.  

This fix has been in the 0.18pre branch for a while.  This would be easier than trying to resolve all the open issue in 0.18 branch.

### CODE REVIEW

**Comment by zsiddique** [comment]
The test failures are due to ruby_dep requiring ruby 2.2 and greater but we have some test running against older ruby version.  The one test passed was against 2.2.5.  I think the fix for that is out of this scope

**Comment by PikachuEXE** [comment]
This very old build on 0.17 branch looks green
https://travis-ci.org/celluloid/celluloid/builds/103210007

But not sure what happens when re-run with latest

**Comment by tarcieri** [comment]
I restarted the build

**Comment by PikachuEXE** [comment]
```
$ rvm use jruby --install --binary --fuzzy
jruby is not installed - installing.
Searching for binary rubies, this might take some time.
Requested binary installation but no rubies are available to download, consider skipping --binary flag.
Gemset '' does not exist, 'rvm jruby do rvm gemset create ' first, or append '--create'.
The command "rvm use jruby --install --binary --fuzzy" failed and exited with 2 during .
```
Not sure Travis issue or Travis config issue

**Comment by PikachuEXE** [comment]
It seems `master` is using a different version of `jruby`
https://travis-ci.org/celluloid/celluloid/builds/299878222

**Comment by myers** [comment]
@tarcieri could you retry the build.  It appears rvm failed to find both rbx and jruby in the last attempt.

I would really like to see a 0.17.4 as it would solve this long yak shave trip I've been on.

**Comment by tarcieri** [comment]
@myers still can't find `rbx-2`. I'm ok with you deleting it, but if the tests pass it'd be nice to have.

**Pull request merged**
